FROM node:latest as build

WORKDIR app/

COPY . .

RUN npm ci --silent
RUN npm install react-scripts --silent

ENV PATH /app/node_modules/.bin:$PATH

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
