name: CI

on: 
  push:
    branches:    
      - master 

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: npm install
      run: |
        npm install
    - name: npm test
      run: |
        npm test 
      env:
        CI: true
    - name: npm build
      run: |
        npm build --if-present
    - name: Add remote origin
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - name: set configuration
      run: |
          heroku config:set REACT_APP_DOMAIN='https://pwnded-app.herokuapp.com'
    - name: Deploy to Heroku
      run: |
        git push heroku HEAD:master -f        
